"""add_infrastructure_buildings_rooms

Revision ID: 0ab205cab979
Revises: df76564f98cd
Create Date: 2026-10-02 21:29:37.006808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ab205cab979'
down_revision: Union[str, Sequence[str], None] = 'df76564f98cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('building_type', sa.Enum('academic', 'hostel', 'administrative', 'facility', name='building_type_enum'), nullable=False),
    sa.Column('total_floors', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buildings_code'), 'buildings', ['code'], unique=True)
    op.create_table('rooms',
    sa.Column('building_id', sa.UUID(), nullable=False),
    sa.Column('room_number', sa.String(length=50), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('room_type', sa.Enum('lecture_hall', 'lab', 'hostel_room', 'faculty_office', 'meeting_room', 'other', name='room_type_enum'), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'room_number', name='uq_building_room_number')
    )
    op.create_index(op.f('ix_rooms_building_id'), 'rooms', ['building_id'], unique=False)
    op.create_index(op.f('ix_rooms_department_id'), 'rooms', ['department_id'], unique=False)
    op.create_index(op.f('ix_rooms_room_number'), 'rooms', ['room_number'], unique=False)
    op.add_column('complaints', sa.Column('building_id', sa.UUID(), nullable=True))
    op.add_column('complaints', sa.Column('room_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_complaints_building_id'), 'complaints', ['building_id'], unique=False)
    op.create_index(op.f('ix_complaints_room_id'), 'complaints', ['room_id'], unique=False)
    op.create_foreign_key('fk_complaints_room_id', 'complaints', 'rooms', ['room_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_complaints_building_id', 'complaints', 'buildings', ['building_id'], ['id'], ondelete='SET NULL')
    op.add_column('student_profiles', sa.Column('room_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_student_profiles_room_id', 'student_profiles', 'rooms', ['room_id'], ['id'], ondelete='SET NULL')
    op.add_column('timetable_slots', sa.Column('room_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_timetable_slots_room_id', 'timetable_slots', 'rooms', ['room_id'], ['id'], ondelete='SET NULL')

    # Seed RBAC Assets & Actions for Infrastructure
    conn = op.get_bind()
    conn.execute(sa.text("INSERT INTO assets (id, name) VALUES (gen_random_uuid(), 'building') ON CONFLICT (name) DO NOTHING;"))
    conn.execute(sa.text("INSERT INTO assets (id, name) VALUES (gen_random_uuid(), 'room') ON CONFLICT (name) DO NOTHING;"))

    for asset in ['building', 'room']:
        for action in ['create', 'view', 'list', 'edit', 'delete']:
            conn.execute(sa.text(f"""
                INSERT INTO permissions (id, asset_id, action_id)
                SELECT gen_random_uuid(), a.id, ac.id
                FROM assets a, actions ac
                WHERE a.name = '{asset}' AND ac.code = '{action}'
                ON CONFLICT ON CONSTRAINT uq_permission_asset_action DO NOTHING;
            """))

    # Grant permissions to SuperAdmin and Admin
    conn.execute(sa.text("""
        INSERT INTO role_permissions (role_id, permission_id)
        SELECT r.id, p.id
        FROM roles r
        CROSS JOIN permissions p
        JOIN assets a ON p.asset_id = a.id
        WHERE r.name IN ('SuperAdmin', 'Admin') AND a.name IN ('building', 'room')
        ON CONFLICT DO NOTHING;
    """))

    # Grant view and list permissions to Faculty and Student
    conn.execute(sa.text("""
        INSERT INTO role_permissions (role_id, permission_id)
        SELECT r.id, p.id
        FROM roles r
        CROSS JOIN permissions p
        JOIN assets a ON p.asset_id = a.id
        JOIN actions ac ON p.action_id = ac.id
        WHERE r.name IN ('Faculty', 'Student') AND a.name IN ('building', 'room') AND ac.code IN ('view', 'list')
        ON CONFLICT DO NOTHING;
    """))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('fk_timetable_slots_room_id', 'timetable_slots', type_='foreignkey')
    op.drop_column('timetable_slots', 'room_id')
    op.drop_constraint('fk_student_profiles_room_id', 'student_profiles', type_='foreignkey')
    op.drop_column('student_profiles', 'room_id')
    op.drop_constraint('fk_complaints_room_id', 'complaints', type_='foreignkey')
    op.drop_constraint('fk_complaints_building_id', 'complaints', type_='foreignkey')
    op.drop_index(op.f('ix_complaints_room_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_building_id'), table_name='complaints')
    op.drop_column('complaints', 'room_id')
    op.drop_column('complaints', 'building_id')
    op.drop_index(op.f('ix_rooms_room_number'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_department_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_building_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_buildings_code'), table_name='buildings')
    op.drop_table('buildings')
    # ### end Alembic commands ###
