"""add description to roles

Revision ID: 12665ebc79c3
Revises: 163f5ade3b53
Create Date: 2026-09-18 19:44:22.997738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12665ebc79c3'
down_revision: Union[str, Sequence[str], None] = '163f5ade3b53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'description')
    # ### end Alembic commands ###
