"""refactor_student_profile_bput_reg_no

Revision ID: 2de1f9788edc
Revises: d9037ee3ff98
Create Date: 2026-10-06 13:11:29.098907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM as PG_ENUM


# revision identifiers, used by Alembic.
revision: str = '2de1f9788edc'
down_revision: Union[str, Sequence[str], None] = 'd9037ee3ff98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mess_scan_logs',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal_type', PG_ENUM('breakfast', 'lunch', 'snacks', 'dinner', name='meal_type_enum', create_type=False), nullable=False),
    sa.Column('scanned_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scanned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'date', 'meal_type', name='uq_mess_scan_student_date_meal')
    )
    op.create_index(op.f('ix_mess_scan_logs_date'), 'mess_scan_logs', ['date'], unique=False)
    op.create_index(op.f('ix_mess_scan_logs_meal_type'), 'mess_scan_logs', ['meal_type'], unique=False)
    op.create_index(op.f('ix_mess_scan_logs_student_id'), 'mess_scan_logs', ['student_id'], unique=False)
    op.add_column('student_profiles', sa.Column('registration_no', sa.String(length=20), nullable=True))
    op.execute("""
        UPDATE student_profiles 
        SET registration_no = '2301230' || LPAD(CAST(sub.seq AS VARCHAR), 3, '0')
        FROM (
            SELECT id, ROW_NUMBER() OVER (ORDER BY created_at, id) as seq 
            FROM student_profiles
        ) sub
        WHERE student_profiles.id = sub.id
    """)
    op.alter_column('student_profiles', 'registration_no', nullable=False)
    op.add_column('student_profiles', sa.Column('roll_no', sa.String(length=30), nullable=True))
    op.add_column('student_profiles', sa.Column('admission_year', sa.Integer(), server_default='2024', nullable=False))
    op.add_column('student_profiles', sa.Column('current_semester', sa.Integer(), server_default='1', nullable=False))
    op.add_column('student_profiles', sa.Column('section', sa.String(length=10), server_default='A', nullable=True))
    op.create_index(op.f('ix_student_profiles_registration_no'), 'student_profiles', ['registration_no'], unique=True)
    op.create_index(op.f('ix_student_profiles_roll_no'), 'student_profiles', ['roll_no'], unique=True)
    op.drop_column('student_profiles', 'hostel')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('hostel', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_student_profiles_roll_no'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_registration_no'), table_name='student_profiles')
    op.drop_column('student_profiles', 'section')
    op.drop_column('student_profiles', 'current_semester')
    op.drop_column('student_profiles', 'admission_year')
    op.drop_column('student_profiles', 'roll_no')
    op.drop_column('student_profiles', 'registration_no')
    op.drop_index(op.f('ix_mess_scan_logs_student_id'), table_name='mess_scan_logs')
    op.drop_index(op.f('ix_mess_scan_logs_meal_type'), table_name='mess_scan_logs')
    op.drop_index(op.f('ix_mess_scan_logs_date'), table_name='mess_scan_logs')
    op.drop_table('mess_scan_logs')
    # ### end Alembic commands ###
