"""add_hod_user_id

Revision ID: 336822464de8
Revises: b7cb69b1a046
Create Date: 2026-09-28 19:14:57.446799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '336822464de8'
down_revision: Union[str, Sequence[str], None] = 'b7cb69b1a046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('hod_user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'departments', 'users', ['hod_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_column('departments', 'hod_user_id')
    # ### end Alembic commands ###
