"""update_role_model

Revision ID: 37cdba93ed53
Revises: 67a06ee6c41e
Create Date: 2026-10-08 21:06:59.374431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37cdba93ed53'
down_revision: Union[str, Sequence[str], None] = '67a06ee6c41e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('code', sa.String(length=50), nullable=False))
    op.add_column('roles', sa.Column('is_system', sa.Boolean(), nullable=False))
    op.add_column('roles', sa.Column('is_assignable', sa.Boolean(), nullable=False))
    op.add_column('roles', sa.Column('status', sa.String(length=50), nullable=False))
    op.drop_constraint(op.f('roles_name_key'), 'roles', type_='unique')
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.drop_column('roles', 'is_system_role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('is_system_role', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.create_unique_constraint(op.f('roles_name_key'), 'roles', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('roles', 'status')
    op.drop_column('roles', 'is_assignable')
    op.drop_column('roles', 'is_system')
    op.drop_column('roles', 'code')
    # ### end Alembic commands ###
