"""migrate_notice_target_hostel_id

Revision ID: 5a84714ef2e6
Revises: 37cdba93ed53
Create Date: 2026-10-09 05:03:44.197393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a84714ef2e6'
down_revision: Union[str, Sequence[str], None] = '37cdba93ed53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hostel_rooms',
    sa.Column('hostel_id', sa.UUID(), nullable=False),
    sa.Column('room_number', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('current_occupancy', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('notices', sa.Column('target_hostel_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_notices_target_hostel_id', 'notices', 'hostels', ['target_hostel_id'], ['id'], ondelete='CASCADE')
    op.drop_column('notices', 'target_hostel')
    op.alter_column('users', 'last_login_at',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.DateTime(timezone=True),
               postgresql_using="last_login_at::timestamp with time zone",
               existing_nullable=True)
    op.alter_column('users', 'deleted_at',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.DateTime(timezone=True),
               postgresql_using="deleted_at::timestamp with time zone",
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('users', 'last_login_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.add_column('notices', sa.Column('target_hostel', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint('fk_notices_target_hostel_id', 'notices', type_='foreignkey')
    op.drop_column('notices', 'target_hostel_id')
    op.drop_table('hostel_rooms')
    # ### end Alembic commands ###
