"""add_hostel_and_update_complaints

Revision ID: 67a06ee6c41e
Revises: 7c68edc34336
Create Date: 2026-10-08 21:05:16.984536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67a06ee6c41e'
down_revision: Union[str, Sequence[str], None] = '7c68edc34336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hostels',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('warden_user_id', sa.UUID(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['warden_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hostels_name'), 'hostels', ['name'], unique=True)
    op.add_column('complaints', sa.Column('hostel_id', sa.UUID(), nullable=True))
    op.add_column('complaints', sa.Column('room_number', sa.String(length=20), nullable=True))
    op.drop_index(op.f('ix_complaints_location_hostel'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_location_room'), table_name='complaints')
    op.create_index(op.f('ix_complaints_hostel_id'), 'complaints', ['hostel_id'], unique=False)
    op.create_index(op.f('ix_complaints_room_number'), 'complaints', ['room_number'], unique=False)
    op.create_foreign_key(None, 'complaints', 'hostels', ['hostel_id'], ['id'], ondelete='SET NULL')
    op.drop_column('complaints', 'location_room')
    op.drop_column('complaints', 'location_hostel')
    op.add_column('student_profiles', sa.Column('hostel_id', sa.UUID(), nullable=True))
    op.add_column('student_profiles', sa.Column('room_number', sa.String(length=20), nullable=True))
    op.create_foreign_key(None, 'student_profiles', 'hostels', ['hostel_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'student_profiles', type_='foreignkey')
    op.drop_column('student_profiles', 'room_number')
    op.drop_column('student_profiles', 'hostel_id')
    op.add_column('complaints', sa.Column('location_hostel', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('complaints', sa.Column('location_room', sa.VARCHAR(), autoincrement=False, nullable=True))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_index(op.f('ix_complaints_room_number'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_hostel_id'), table_name='complaints')
    op.create_index(op.f('ix_complaints_location_room'), 'complaints', ['location_room'], unique=False)
    op.create_index(op.f('ix_complaints_location_hostel'), 'complaints', ['location_hostel'], unique=False)
    op.drop_column('complaints', 'room_number')
    op.drop_column('complaints', 'hostel_id')
    op.drop_index(op.f('ix_hostels_name'), table_name='hostels')
    op.drop_table('hostels')
    # ### end Alembic commands ###
