"""add_phase_4_models

Revision ID: 7c68edc34336
Revises: 5102c9951c0c
Create Date: 2026-10-08 20:53:07.411524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c68edc34336'
down_revision: Union[str, Sequence[str], None] = '5102c9951c0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_types',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('template_file_url', sa.String(length=1000), nullable=True),
    sa.Column('fields_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('approval_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fee', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_types_code'), 'document_types', ['code'], unique=True)
    op.create_table('map_locations',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('building', 'classroom', 'lab', 'hostel', 'library', 'canteen', 'gate', 'office', 'ground', 'parking', 'other', name='location_type_enum'), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geometry', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['map_locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_map_locations_code'), 'map_locations', ['code'], unique=True)
    op.create_table('map_paths',
    sa.Column('from_location_id', sa.UUID(), nullable=False),
    sa.Column('to_location_id', sa.UUID(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('path_geojson', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('accessible', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_location_id'], ['map_locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_location_id'], ['map_locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_conversations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_requests',
    sa.Column('type_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('form_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('submitted', 'in_review', 'needs_revision', 'approved', 'rejected', 'issued', name='document_request_status_enum'), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('issued_file_url', sa.String(length=1000), nullable=True),
    sa.Column('verify_code', sa.String(length=255), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['document_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_requests_verify_code'), 'document_requests', ['verify_code'], unique=True)
    op.create_table('gate_passes',
    sa.Column('student_user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('short', 'long', name='gate_pass_type_enum'), nullable=False),
    sa.Column('reason_category', sa.Enum('tea', 'market', 'medical', 'holiday', 'other', name='gate_pass_reason_enum'), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_return_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('from_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('to_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('requested', 'approved', 'rejected', 'cancelled', 'out', 'returned', 'overdue', 'expired', name='gate_pass_status_enum'), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('review_note', sa.String(length=1000), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pass_code', sa.String(length=255), nullable=True),
    sa.Column('actual_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_return_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('marked_out_by', sa.UUID(), nullable=True),
    sa.Column('marked_in_by', sa.UUID(), nullable=True),
    sa.Column('parent_notified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['marked_in_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['marked_out_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gate_passes_pass_code'), 'gate_passes', ['pass_code'], unique=True)
    op.create_table('placement_notices',
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('package_text', sa.String(length=255), nullable=True),
    sa.Column('eligible_course_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('eligible_department_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('min_cgpa', sa.Float(), nullable=True),
    sa.Column('passout_year', sa.Integer(), nullable=True),
    sa.Column('last_date', sa.Date(), nullable=True),
    sa.Column('drive_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'closed', name='placement_notice_status_enum'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_silent_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('mode', sa.Enum('silent', 'vibrate', 'dnd', name='silent_mode_enum'), nullable=False),
    sa.Column('source', sa.Enum('timetable', 'custom', 'both', name='silent_source_enum'), nullable=False),
    sa.Column('minutes_before', sa.Integer(), nullable=False),
    sa.Column('minutes_after', sa.Integer(), nullable=False),
    sa.Column('allow_emergency', sa.Boolean(), nullable=False),
    sa.Column('custom_ranges', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('ai_messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('system', 'user', 'assistant', 'tool', name='ai_message_role_enum'), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_approvals',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=False),
    sa.Column('approver_user_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approver_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['request_id'], ['document_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('placement_applications',
    sa.Column('notice_id', sa.UUID(), nullable=False),
    sa.Column('student_user_id', sa.UUID(), nullable=False),
    sa.Column('resume_url', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('applied', 'shortlisted', 'rejected', 'selected', name='placement_application_status_enum'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notice_id'], ['placement_notices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timetable_slots',
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('class_group_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('faculty_user_id', sa.UUID(), nullable=False),
    sa.Column('room_location_id', sa.UUID(), nullable=True),
    sa.Column('day_of_week', sa.Enum('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', name='day_of_week_enum'), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_group_id'], ['class_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faculty_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['academic_terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance_sessions',
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('taken_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['slot_id'], ['timetable_slots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['taken_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timetable_exceptions',
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('cancelled', 'substitute', 'extra', name='exception_type_enum'), nullable=False),
    sa.Column('substitute_faculty_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['slot_id'], ['timetable_slots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['substitute_faculty_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance_records',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('student_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('present', 'absent', 'late', 'excused', name='attendance_status_enum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance_records')
    op.drop_table('timetable_exceptions')
    op.drop_table('attendance_sessions')
    op.drop_table('timetable_slots')
    op.drop_table('placement_applications')
    op.drop_table('document_approvals')
    op.drop_table('ai_messages')
    op.drop_table('user_silent_settings')
    op.drop_table('placement_notices')
    op.drop_index(op.f('ix_gate_passes_pass_code'), table_name='gate_passes')
    op.drop_table('gate_passes')
    op.drop_index(op.f('ix_document_requests_verify_code'), table_name='document_requests')
    op.drop_table('document_requests')
    op.drop_table('ai_conversations')
    op.drop_table('map_paths')
    op.drop_index(op.f('ix_map_locations_code'), table_name='map_locations')
    op.drop_table('map_locations')
    op.drop_index(op.f('ix_document_types_code'), table_name='document_types')
    op.drop_table('document_types')
    # ### end Alembic commands ###
