"""move_name_to_user

Revision ID: 8098a92bb9ef
Revises: fcf623c50bf8
Create Date: 2026-09-17 01:04:26.649304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8098a92bb9ef'
down_revision: Union[str, Sequence[str], None] = 'fcf623c50bf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=True))
    
    # Migrate data from student_profiles
    op.execute("""
        UPDATE users
        SET name = student_profiles.name
        FROM student_profiles
        WHERE users.id = student_profiles.user_id
          AND student_profiles.name IS NOT NULL
    """)
    
    # Migrate data from faculty_profiles
    op.execute("""
        UPDATE users
        SET name = faculty_profiles.name
        FROM faculty_profiles
        WHERE users.id = faculty_profiles.user_id
          AND faculty_profiles.name IS NOT NULL
    """)

    # Drop old columns
    op.drop_column('faculty_profiles', 'name')
    op.drop_column('student_profiles', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.add_column('student_profiles', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('faculty_profiles', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
