"""add_outpass_models

Revision ID: 89433e6246a9
Revises: a8f3b0033ac8
Create Date: 2026-09-15 21:47:40.762418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89433e6246a9'
down_revision: Union[str, Sequence[str], None] = 'a8f3b0033ac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outpasses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('departure_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_return_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_return_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'active', 'completed', 'rejected', 'cancelled', name='outpass_status_enum'), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outpasses_status'), 'outpasses', ['status'], unique=False)
    op.create_index(op.f('ix_outpasses_student_id'), 'outpasses', ['student_id'], unique=False)
    op.create_table('outpass_status_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('outpass_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'active', 'completed', 'rejected', 'cancelled', name='outpass_status_enum'), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['outpass_id'], ['outpasses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outpass_status_logs_outpass_id'), 'outpass_status_logs', ['outpass_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outpass_status_logs_outpass_id'), table_name='outpass_status_logs')
    op.drop_table('outpass_status_logs')
    op.drop_index(op.f('ix_outpasses_student_id'), table_name='outpasses')
    op.drop_index(op.f('ix_outpasses_status'), table_name='outpasses')
    op.drop_table('outpasses')
    # ### end Alembic commands ###
