"""expand system settings

Revision ID: 926c79793124
Revises: f76f3d21a230
Create Date: 2026-09-20 22:01:43.744057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '926c79793124'
down_revision: Union[str, Sequence[str], None] = 'f76f3d21a230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('category', sa.String(length=50), nullable=False, server_default='General'))
    op.add_column('system_settings', sa.Column('data_type', sa.String(length=20), nullable=False, server_default='string'))
    op.add_column('system_settings', sa.Column('is_public', sa.Boolean(), nullable=False, server_default='false'))
    op.alter_column('system_settings', 'value',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=2000),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_settings', 'value',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=1000),
               nullable=False)
    op.drop_column('system_settings', 'is_public')
    op.drop_column('system_settings', 'data_type')
    op.drop_column('system_settings', 'category')
    # ### end Alembic commands ###
