"""extend_notices

Revision ID: a8f3b0033ac8
Revises: 2070af1ad809
Create Date: 2026-09-15 16:38:18.400878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8f3b0033ac8'
down_revision: Union[str, Sequence[str], None] = '2070af1ad809'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notice_reads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notice_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('notices', sa.Column('target_year', sa.Integer(), nullable=True))
    op.add_column('notices', sa.Column('target_hostel', sa.String(length=255), nullable=True))
    op.add_column('notices', sa.Column('target_user_types', sa.String(length=255), nullable=True))
    op.add_column('student_profiles', sa.Column('hostel', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profiles', 'hostel')
    op.drop_column('notices', 'target_user_types')
    op.drop_column('notices', 'target_hostel')
    op.drop_column('notices', 'target_year')
    op.drop_table('notice_reads')
    # ### end Alembic commands ###
