"""implement_role_applications

Revision ID: b34399b01cb5
Revises: c8a87009d512
Create Date: 2026-10-08 18:21:52.077223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b34399b01cb5'
down_revision: Union[str, Sequence[str], None] = 'c8a87009d512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_applications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('form_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('submitted', 'needs_revision', 'approved', 'rejected', name='application_status_enum'), nullable=False),
    sa.Column('review_note', sa.String(length=1000), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('faculty_profiles', sa.Column('faculty_id', sa.String(length=50), nullable=False))
    op.add_column('faculty_profiles', sa.Column('join_year', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_faculty_profiles_employee_id'), table_name='faculty_profiles')
    op.create_index(op.f('ix_faculty_profiles_faculty_id'), 'faculty_profiles', ['faculty_id'], unique=True)
    op.drop_column('faculty_profiles', 'employee_id')
    op.add_column('parent_profiles', sa.Column('emergency_name', sa.String(length=255), nullable=True))
    op.add_column('parent_profiles', sa.Column('emergency_phone', sa.String(length=20), nullable=True))
    op.drop_column('parent_profiles', 'emergency_contact')
    op.add_column('staff_profiles', sa.Column('staff_id', sa.String(length=50), nullable=False))
    op.add_column('staff_profiles', sa.Column('join_year', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_staff_profiles_employee_id'), table_name='staff_profiles')
    op.create_index(op.f('ix_staff_profiles_staff_id'), 'staff_profiles', ['staff_id'], unique=True)
    op.drop_column('staff_profiles', 'employee_id')
    op.drop_index(op.f('ix_student_profiles_roll_no'), table_name='student_profiles')
    op.drop_column('student_profiles', 'roll_no')
    op.drop_column('users', 'application_data')
    op.drop_column('users', 'target_role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('target_role', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('application_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('student_profiles', sa.Column('roll_no', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_student_profiles_roll_no'), 'student_profiles', ['roll_no'], unique=True)
    op.add_column('staff_profiles', sa.Column('employee_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_staff_profiles_staff_id'), table_name='staff_profiles')
    op.create_index(op.f('ix_staff_profiles_employee_id'), 'staff_profiles', ['employee_id'], unique=True)
    op.drop_column('staff_profiles', 'join_year')
    op.drop_column('staff_profiles', 'staff_id')
    op.add_column('parent_profiles', sa.Column('emergency_contact', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('parent_profiles', 'emergency_phone')
    op.drop_column('parent_profiles', 'emergency_name')
    op.add_column('faculty_profiles', sa.Column('employee_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_faculty_profiles_faculty_id'), table_name='faculty_profiles')
    op.create_index(op.f('ix_faculty_profiles_employee_id'), 'faculty_profiles', ['employee_id'], unique=True)
    op.drop_column('faculty_profiles', 'join_year')
    op.drop_column('faculty_profiles', 'faculty_id')
    op.drop_table('role_applications')
    # ### end Alembic commands ###
