"""add_department_type

Revision ID: b7cb69b1a046
Revises: 60a8fc13b106
Create Date: 2026-09-28 15:41:17.344734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7cb69b1a046'
down_revision: Union[str, Sequence[str], None] = '60a8fc13b106'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    departmenttype = sa.Enum('academic', 'administrative', name='departmenttype')
    departmenttype.create(op.get_bind(), checkfirst=True)
    
    op.add_column('departments', sa.Column('department_type', departmenttype, server_default='academic', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'department_type')
    
    departmenttype = sa.Enum('academic', 'administrative', name='departmenttype')
    departmenttype.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
