"""Add user preferences

Revision ID: c3c46dab3bef
Revises: bfb436c22d09
Create Date: 2026-09-20 21:36:20.478109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3c46dab3bef'
down_revision: Union[str, Sequence[str], None] = 'bfb436c22d09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_notifications', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('in_app_alerts', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'in_app_alerts')
    op.drop_column('users', 'email_notifications')
    # ### end Alembic commands ###
