"""Phase 5: Mess Module

Revision ID: d8a14afedeb3
Revises: 2de99b7c5cf2
Create Date: 2026-09-16 01:18:19.947784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8a14afedeb3'
down_revision: Union[str, Sequence[str], None] = '2de99b7c5cf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mess_menu',
    sa.Column('day_of_week', sa.Enum('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', name='day_of_week_enum'), nullable=False),
    sa.Column('meal_type', sa.Enum('breakfast', 'lunch', 'snacks', 'dinner', name='meal_type_enum'), nullable=False),
    sa.Column('items', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day_of_week', 'meal_type', name='uq_mess_menu_day_meal')
    )
    op.create_table('mess_feedback',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.Enum('breakfast', 'lunch', 'snacks', 'dinner', name='meal_type_enum'), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'date', 'meal_type', name='uq_mess_feedback_student_date_meal')
    )
    op.create_index(op.f('ix_mess_feedback_date'), 'mess_feedback', ['date'], unique=False)
    op.create_index(op.f('ix_mess_feedback_meal_type'), 'mess_feedback', ['meal_type'], unique=False)
    op.create_table('mess_optout',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.Enum('breakfast', 'lunch', 'snacks', 'dinner', name='meal_type_enum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'date', 'meal_type', name='uq_mess_optout_student_date_meal')
    )
    op.create_index(op.f('ix_mess_optout_date'), 'mess_optout', ['date'], unique=False)
    op.create_index(op.f('ix_mess_optout_meal_type'), 'mess_optout', ['meal_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mess_optout_meal_type'), table_name='mess_optout')
    op.drop_index(op.f('ix_mess_optout_date'), table_name='mess_optout')
    op.drop_table('mess_optout')
    op.drop_index(op.f('ix_mess_feedback_meal_type'), table_name='mess_feedback')
    op.drop_index(op.f('ix_mess_feedback_date'), table_name='mess_feedback')
    op.drop_table('mess_feedback')
    op.drop_table('mess_menu')
    # ### end Alembic commands ###
