"""Add missing tables

Revision ID: d9037ee3ff98
Revises: e6ed381c4862
Create Date: 2026-10-05 18:30:52.495250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9037ee3ff98'
down_revision: Union[str, Sequence[str], None] = 'e6ed381c4862'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_link_requests',
    sa.Column('parent_user_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'revoked', name='parent_link_status_enum'), nullable=False),
    sa.Column('share_gate_pass', sa.Boolean(), nullable=False),
    sa.Column('share_attendance', sa.Boolean(), nullable=False),
    sa.Column('share_marksheet', sa.Boolean(), nullable=False),
    sa.Column('share_outpass', sa.Boolean(), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parent_link_requests_parent_user_id'), 'parent_link_requests', ['parent_user_id'], unique=False)
    op.create_index(op.f('ix_parent_link_requests_status'), 'parent_link_requests', ['status'], unique=False)
    op.create_index(op.f('ix_parent_link_requests_student_id'), 'parent_link_requests', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_actor_id_fkey'), 'audit_logs', 'users', ['actor_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_parent_link_requests_student_id'), table_name='parent_link_requests')
    op.drop_index(op.f('ix_parent_link_requests_status'), table_name='parent_link_requests')
    op.drop_index(op.f('ix_parent_link_requests_parent_user_id'), table_name='parent_link_requests')
    op.drop_table('parent_link_requests')
    # ### end Alembic commands ###
