"""add_document_requests_tables

Revision ID: df76564f98cd
Revises: 60a8fc13b106
Create Date: 2026-10-02 21:13:54.671008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df76564f98cd'
down_revision: Union[str, Sequence[str], None] = '60a8fc13b106'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_requests',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('bonafide', 'noc', 'fee_clearance', 'character_certificate', 'transcript', 'other', name='document_type_enum'), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'ready', name='document_status_enum'), nullable=False),
    sa.Column('urgency', sa.Enum('normal', 'urgent', name='document_urgency_enum'), nullable=False),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('issued_file_url', sa.String(length=500), nullable=True),
    sa.Column('processed_by', sa.UUID(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_status_logs',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['document_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Seed RBAC Asset & Permissions for Documents
    conn = op.get_bind()
    conn.execute(sa.text("INSERT INTO assets (id, name) VALUES (gen_random_uuid(), 'document') ON CONFLICT (name) DO NOTHING;"))
    
    # Ensure actions exist
    for action in ["create", "view", "list", "approve", "reject", "manage"]:
        conn.execute(sa.text(f"INSERT INTO actions (id, code) VALUES (gen_random_uuid(), '{action}') ON CONFLICT (code) DO NOTHING;"))

    # Create permissions
    for action in ["create", "view", "list", "approve", "reject", "manage"]:
        conn.execute(sa.text(f"""
            INSERT INTO permissions (id, asset_id, action_id)
            SELECT gen_random_uuid(), a.id, ac.id
            FROM assets a, actions ac
            WHERE a.name = 'document' AND ac.code = '{action}'
            ON CONFLICT ON CONSTRAINT uq_permission_asset_action DO NOTHING;
        """))

    # Grant document permissions to SuperAdmin and Admin
    conn.execute(sa.text("""
        INSERT INTO role_permissions (role_id, permission_id)
        SELECT r.id, p.id
        FROM roles r
        CROSS JOIN permissions p
        JOIN assets a ON p.asset_id = a.id
        WHERE r.name IN ('SuperAdmin', 'Admin') AND a.name = 'document'
        ON CONFLICT DO NOTHING;
    """))

    # Grant student role document:create, document:view, document:list
    conn.execute(sa.text("""
        INSERT INTO role_permissions (role_id, permission_id)
        SELECT r.id, p.id
        FROM roles r
        CROSS JOIN permissions p
        JOIN assets a ON p.asset_id = a.id
        JOIN actions ac ON p.action_id = ac.id
        WHERE r.name = 'Student' AND a.name = 'document' AND ac.code IN ('create', 'view')
        ON CONFLICT DO NOTHING;
    """))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('document_status_logs')
    op.drop_table('document_requests')
