"""embed_target_role_and_application_data_in_users

Revision ID: e6ed381c4862
Revises: 07409fdae37c
Create Date: 2026-10-05 16:45:46.182210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6ed381c4862'
down_revision: Union[str, Sequence[str], None] = '07409fdae37c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quick_gate_passes',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('pass_code', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Enum('tea_snack', 'market_errand', 'walk_exercise', 'personal_work', 'other', name='gate_pass_reason_enum'), nullable=False),
    sa.Column('custom_reason', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('checked_out', 'checked_in', 'overdue', 'cancelled', name='gate_pass_status_enum'), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expected_return_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_return_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scanned_out_by', sa.UUID(), nullable=True),
    sa.Column('scanned_in_by', sa.UUID(), nullable=True),
    sa.Column('emergency_alert_sent', sa.Boolean(), nullable=False),
    sa.Column('qr_token_hash', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scanned_in_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scanned_out_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quick_gate_passes_expected_return_time'), 'quick_gate_passes', ['expected_return_time'], unique=False)
    op.create_index(op.f('ix_quick_gate_passes_pass_code'), 'quick_gate_passes', ['pass_code'], unique=True)
    op.create_index(op.f('ix_quick_gate_passes_status'), 'quick_gate_passes', ['status'], unique=False)
    op.create_index(op.f('ix_quick_gate_passes_student_id'), 'quick_gate_passes', ['student_id'], unique=False)
    op.drop_index(op.f('ix_role_applications_status'), table_name='role_applications', if_exists=True)
    op.drop_index(op.f('ix_role_applications_user_id'), table_name='role_applications', if_exists=True)
    op.execute("DROP TABLE IF EXISTS role_applications CASCADE")
    op.add_column('users', sa.Column('target_role', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('application_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'application_data')
    op.drop_column('users', 'target_role')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # op.drop_constraint('audit_logs_actor_id_fkey', 'audit_logs', type_='foreignkey')

    op.create_foreign_key(op.f('audit_logs_actor_id_fkey'), 'audit_logs', 'users', ['actor_id'], ['id'], ondelete='CASCADE')
    op.create_table('role_applications',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('target_role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('application_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'approved', 'rejected', 'revision', name='application_status_enum'), autoincrement=False, nullable=False),
    sa.Column('admin_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reviewed_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('role_applications_reviewed_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('role_applications_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('role_applications_pkey'))
    )
    op.create_index(op.f('ix_role_applications_user_id'), 'role_applications', ['user_id'], unique=False)
    op.create_index(op.f('ix_role_applications_status'), 'role_applications', ['status'], unique=False)
    op.drop_index(op.f('ix_quick_gate_passes_student_id'), table_name='quick_gate_passes')
    op.drop_index(op.f('ix_quick_gate_passes_status'), table_name='quick_gate_passes')
    op.drop_index(op.f('ix_quick_gate_passes_pass_code'), table_name='quick_gate_passes')
    op.drop_index(op.f('ix_quick_gate_passes_expected_return_time'), table_name='quick_gate_passes')
    op.drop_table('quick_gate_passes')
    # ### end Alembic commands ###
