"""move_photo_url_to_user

Revision ID: fcf623c50bf8
Revises: 0c8f91795dca
Create Date: 2026-09-17 00:08:35.280055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcf623c50bf8'
down_revision: Union[str, Sequence[str], None] = '0c8f91795dca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column first
    op.add_column('users', sa.Column('photo_url', sa.String(length=255), nullable=True))
    
    # Migrate data from student_profiles
    op.execute("""
        UPDATE users
        SET photo_url = student_profiles.photo_url
        FROM student_profiles
        WHERE users.id = student_profiles.user_id
          AND student_profiles.photo_url IS NOT NULL
    """)
    
    # Migrate data from faculty_profiles
    op.execute("""
        UPDATE users
        SET photo_url = faculty_profiles.photo_url
        FROM faculty_profiles
        WHERE users.id = faculty_profiles.user_id
          AND faculty_profiles.photo_url IS NOT NULL
    """)

    # Drop old columns
    op.drop_column('faculty_profiles', 'photo_url')
    op.drop_column('student_profiles', 'photo_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'photo_url')
    op.add_column('student_profiles', sa.Column('photo_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('faculty_profiles', sa.Column('photo_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
